#ifndef GAME_DATA_H
#define GAME_DATA_H

#define MAP_WIDTH 12
#define MAP_HEIGHT 15
#define DEFAULT_FOOD_SPAWN_INTERVAL 3000
#define TICK 2
#define TIME_PER_TICK 1.0/TICK
#define MAX_PLAYER_COUNT 2
#define NEURTAL_PLAYER_ID 12
#define PLAYER_1_ID 0
#define PLAYER_2_ID 1
#define PLAYER_UNKNOWN_ID -1

#define NAME_LENGTH 32

#endif